-- USERS ------------------------------------------------------------
CREATE TABLE users (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(100)  NOT NULL,
  email            VARCHAR(150)  NOT NULL,
  hashed_password  VARCHAR(255)  NOT NULL,
  role             VARCHAR(30)   NOT NULL
);

-- unique email (entity has unique=true)
ALTER TABLE users
  ADD CONSTRAINT uk_users_email UNIQUE (email);


-- CATEGORIES -------------------------------------------------------
-- maps com.example.finance.model.Category
-- owner is nullable for global/shared categories
CREATE TABLE categories (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code    VARCHAR(20),
  user_id BIGINT,              -- Category.owner
  name    VARCHAR(30)  NOT NULL,
  color   VARCHAR(20),
  icon    VARCHAR(20),
  kind    VARCHAR(20)  NOT NULL
    CHECK (kind IN ('EXPENSE','INCOME', 'SAVING'))
);

-- FKs & indexes as per @ManyToOne and @Index
ALTER TABLE categories
  ADD CONSTRAINT fk_categories_user
  FOREIGN KEY (user_id) REFERENCES users(id);

-- unique (user_id, name) and unique (code) as in @Table(uniqueConstraints=...)
ALTER TABLE categories
  ADD CONSTRAINT uk_category_user_name UNIQUE (user_id, name);

ALTER TABLE categories
  ADD CONSTRAINT uk_category_code UNIQUE (code);

-- index for findAllByOwnerId / findAllByOwnerIdIsNull
CREATE INDEX idx_categories_user ON categories(user_id);


-- TRANSACTIONS -----------------------------------------------------
-- maps com.example.finance.model.Transaction
CREATE TABLE transactions (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount            NUMERIC(19,2) NOT NULL,
  transaction_date  DATE          NOT NULL,
  description       VARCHAR(150),
  user_id           BIGINT        NOT NULL,
  category_id       BIGINT        NOT NULL,
  type              VARCHAR(255)  NOT NULL
    CHECK (type IN ('EXPENSE','INCOME', 'SAVING'))
);

-- FKs
ALTER TABLE transactions
  ADD CONSTRAINT fk_transactions_user
  FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE transactions
  ADD CONSTRAINT fk_transactions_category
  FOREIGN KEY (category_id) REFERENCES categories(id);

-- indexes used by your repo queries
CREATE INDEX idx_transactions_user     ON transactions(user_id);
CREATE INDEX idx_transactions_category ON transactions(category_id);
CREATE INDEX idx_transactions_date     ON transactions(transaction_date);
